import '../models/collection_model.dart';
import '../models/wishlist_item.dart';

class MockData {
  MockData._();

  static final List<CollectionModel> sampleCollections = [
    CollectionModel(
      id: 'col_dream',
      name: 'Dream List',
      emoji: '✨',
      coverImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
      accentColorHex: '#B8324A',
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
    ),
    CollectionModel(
      id: 'col_fashion',
      name: 'Fashion',
      emoji: '👗',
      coverImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80',
      accentColorHex: '#E29578',
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
    ),
    CollectionModel(
      id: 'col_home',
      name: 'Home & Living',
      emoji: '🏠',
      coverImage: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80',
      accentColorHex: '#8A9A86',
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
    ),
    CollectionModel(
      id: 'col_tech',
      name: 'Tech & Audio',
      emoji: '🎧',
      coverImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      accentColorHex: '#7A9E9F',
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
    ),
    CollectionModel(
      id: 'col_gifts',
      name: 'Gift Ideas',
      emoji: '🎁',
      coverImage: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
      accentColorHex: '#D4A373',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
    ),
  ];

  static final List<WishlistItem> sampleItems = [
    WishlistItem(
      id: 'item_1',
      title: 'Bang & Olufsen Beoplay H95 Kulaklık',
      imagePath: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      price: 32900.0,
      currency: '₺',
      store: 'Bang & Olufsen TR',
      productUrl: 'https://www.bang-olufsen.com',
      collectionId: 'col_tech',
      notes: 'Lüks titanyum serisi. Seyahatler ve odaklanma saatleri için harika pasif gürültü engelleme.',
      priority: ItemPriority.high,
      isFavorite: true,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    WishlistItem(
      id: 'item_2',
      title: 'Maison Francis Kurkdjian Baccarat Rouge 540',
      imagePath: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80',
      price: 14500.0,
      currency: '₺',
      store: 'Beymen',
      productUrl: 'https://www.beymen.com',
      collectionId: 'col_fashion',
      notes: '70ml Extrait de Parfum. Sıcak odunsu ve kehribar notaları.',
      priority: ItemPriority.high,
      isFavorite: true,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    WishlistItem(
      id: 'item_3',
      title: 'Vitra Eames Lounge Chair & Ottoman',
      imagePath: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80',
      price: 245000.0,
      currency: '₺',
      store: 'Mozaik Design',
      productUrl: 'https://www.mozaikdesign.com',
      collectionId: 'col_home',
      notes: 'Siyah deri ve ceviz kaplama ikonik tasarım sandalye. Salon okuma köşesi için hayal parça.',
      priority: ItemPriority.medium,
      isFavorite: false,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    WishlistItem(
      id: 'item_4',
      title: 'Leica M11 Rangefinder Kamera Body',
      imagePath: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
      price: 340000.0,
      currency: '₺',
      store: 'Leica Store Istanbul',
      productUrl: 'https://leica-camera.com',
      collectionId: 'col_dream',
      notes: '60MP BSI CMOS Sensör. Siyah kaplama minimalist tasarım.',
      priority: ItemPriority.high,
      isFavorite: true,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    WishlistItem(
      id: 'item_5',
      title: 'Acne Studios Oversized Wool Scarf',
      imagePath: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=800&q=80',
      price: 8900.0,
      currency: '₺',
      store: 'Vakkorama',
      productUrl: 'https://www.vakkorama.com.tr',
      collectionId: 'col_fashion',
      notes: 'Krem ve pastel pembe kareli yumuşak yün atkı.',
      priority: ItemPriority.low,
      isFavorite: false,
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
    ),
    WishlistItem(
      id: 'item_6',
      title: 'Smeg Espresso Kahve Makinesi (Krem)',
      imagePath: 'https://images.unsplash.com/photo-1517668808822-9ebe02afd2a1?auto=format&fit=crop&w=800&q=80',
      price: 18490.0,
      currency: '₺',
      store: 'Enplus',
      productUrl: 'https://www.enplus.com.tr',
      collectionId: 'col_home',
      notes: '50’ler retro tarzı mat krem renkli manometreli espresso makinesi.',
      priority: ItemPriority.medium,
      isFavorite: true,
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
    ),
  ];
}
